# Generated by Django 2.1.4 on 2018-12-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belegungen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lehrveranstaltung',
            name='stud',
        ),
    ]
