# Generated by Django 2.1.4 on 2018-12-20 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belegungen', '0004_auto_20181214_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studierendenliste',
            name='studenten',
        ),
        migrations.AddField(
            model_name='studierendenliste',
            name='studenten',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='belegungen.Student'),
        ),
    ]
