# Generated by Django 2.1.4 on 2018-12-14 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lehrveranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv_nr', models.IntegerField(default=100)),
                ('lv_name', models.CharField(max_length=200)),
                ('doz_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrikel_nr', models.IntegerField(default=0)),
                ('stud_name', models.CharField(max_length=150)),
                ('stud_vorname', models.CharField(max_length=150)),
                ('lv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belegungen.Lehrveranstaltung')),
            ],
        ),
        migrations.AddField(
            model_name='lehrveranstaltung',
            name='stud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belegungen.Student'),
        ),
    ]
